### ISSUE TITLE
Where is dmm_orignal?

### ISSUE THREAD

**Issue by hsm207** [barronalex/Dynamic-Memory-Networks-in-TensorFlow#10]
In line 24 of the dmm_train.py module, we have:

```
if dmn_type == "original":
    from dmn_original import Config
    config = Config()
elif dmn_type == "plus":
    from dmn_plus import Config
    config = Config()
else:
    raise NotImplementedError(dmn_type + ' DMN type is not currently implemented')
```
but there is no file named dmm_original.py.

**Comment by barronalex** [comment]
I ended up removing it from the repo since it performs far worse than the DMN+.
It implemented the architecture described in https://arxiv.org/abs/1506.07285.
