### ISSUE TITLE
This code cannot train task7 successfully, where there are varied number of supporting facts for each question.

### ISSUE THREAD

**Issue by JaneShenYY** [barronalex/Dynamic-Memory-Networks-in-TensorFlow#13]
HI, this code cannot train task 7 successfully. task 7 has varied number of supporting facts for different questions. I think the variable **_rel_labels_** doesn't handle it well. rel_label.shape is (10000,), so when try to access to rel_shape[1]. The index out of range occurred.

```
  File "H:\Research\Codes\Dynamic-Memory-Networks-in-TensorFlow-master\babi_input.py", line 316, in load_babi
    return train, valid, word_embedding, max_q_len, max_input_len, max_mask_len, rel_labels.shape[1], len(vocab)
IndexError: tuple index out of range`
```

How to fix it?

**Comment by barronalex** [comment]
Since strong supervision is disabled and you get good performance without it, I ended up just removing that capability in 9982c96580c258a72704eb16e11fb62c248721e6.

Task 7 should train successfully now.

**Comment by JaneShenYY** [comment]
Thanks.
