### ISSUE TITLE
Change tf.split to tf.unstack

### ISSUE THREAD

**Issue by zhhtc200** [barronalex/Dynamic-Memory-Networks-in-TensorFlow#2]
I think tf.split is not the same as it used to be.

For examples,
> inputs = tf.split(inputs, self.max_input_len, axis=1)
> inputs = [tf.squeeze(i, squeeze_dims=[1]) for i in inputs]

can be replaced with

> inputs = tf.unstack(inputs, self.max_input_len, axis=1)

and 
> softs = tf.split(softs, self.max_input_len, axis=1)

should be

> softs = tf.split(softs, [1]*self.max_input_len, axis=1)

**Comment by barronalex** [comment]
Ah thanks for the heads up!

I slotted in tf.unstack as you suggested. I think the other uses of tf.split are equivalent though so I've left them as is.

**Comment by zhhtc200** [comment]
Python outputs some errors when I use `softs = tf.split(softs, self.max_input_len, axis=1)`. I don't think it is equivalent. You can check the recent Tensorflow r1.0 docs to see the difference.

My environment is Ubuntu 16.04, python 3.5 with anaconda with tensorflow-gpu r1.0

**Comment by barronalex** [comment]
Hmm, I did check the docs and test the code on my machine. It seems you can still pass an integer to tf.split there's just now the additional option to pass an array as above.

I'm running python 2.7 rather than 3.5 so I assume that's where the error is coming from?

**Comment by zhhtc200** [comment]
After debugging this error, I found what is wrong in this case. You are right. The error is due to the Python 3 division. I change the code to the following and solve the problem.
`softs = tf.split(softs, int(self.max_input_len), axis=1)`
