### ISSUE TITLE
tf error

### ISSUE THREAD

**Issue by unsupervis** [barronalex/Dynamic-Memory-Networks-in-TensorFlow#3]
getting this error.. i suppose something to do with the recent changes in tensorflow ...i am using 1.1.0

ValueError: Attempt to reuse RNNCell <tensorflow.contrib.rnn.python.ops.core_rnn_cell_impl.GRUCell object at 0x7f69f4de3850> with a different variable scope than its first use.  First use of cell was with scope 'DMN/question/rnn/gru_cell', this attempt is with scope 'DMN/input/bidirectional_rnn/fw/gru_cell'.  Please create a new instance of the cell if you would like it to use a different set of weights.  If before you were using: MultiRNNCell([GRUCell(...)] * num_layers), change to: MultiRNNCell([GRUCell(...) for _ in range(num_layers)]).  If before you were using the same cell instance as both the forward and reverse cell of a bidirectional RNN, simply create two instances (one for forward, one for reverse).  In May 2017, we will start transitioning this cell's behavior to use existing stored weights, if any, when it is called with scope=None (which can lead to silent model degradation, so this error will remain until then.)

**Comment by barronalex** [comment]
Just updated the repository to support TF 1.1 and Python 3 so that should fix your error. Let me know if you still have problems.

**Comment by unsupervis** [comment]
Thanks
