### ISSUE TITLE
Error in sharing variable DMN/memory/attention/dense/kernel

### ISSUE THREAD

**Issue by alexbui91** [barronalex/Dynamic-Memory-Networks-in-TensorFlow#4]
Hi guy, 
I clone your code and run it in my both local pc and gpu server. It keeps occurring this error
"Trying to share variable DMN/memory/attention/dense/kernel, but specified shape (100, 1) and found shape (400, 100)" 
this error comes from these two line:
attention = tf.layers.dense(feature_vec,
                    self.config.embed_size,
                    activation=tf.nn.tanh,
                    reuse=reuse)
                    
 attention = tf.layers.dense(attention,
                    1,
                    activation=None,
                    reuse=reuse)
Do you have any suggestion for me in this case? Thank you very much

**Comment by Arvinds-ds** [comment]
I worked for me by a minor change outlined in PR I submitted below.

https://github.com/barronalex/Dynamic-Memory-Networks-in-TensorFlow/pull/5

**Comment by barronalex** [comment]
Thanks for the pull request! All should be working now.
